In [39]:
import cv2
import os
import numpy as np
from PIL import Image
import os
import shutil
from sklearn.datasets import fetch_lfw_people

## create dataset

In [40]:
source_dir = "./lfw"

destination_dir = "./Other"

In [41]:
faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [42]:
os.makedirs(destination_dir, exist_ok=True)

count = 0
# Iterate through the folders in the source directory
for folder_name in os.listdir(source_dir):
    folder_path = os.path.join(source_dir, folder_name)

    # Skip any non-directory items
    if not os.path.isdir(folder_path):
        continue
    
    # Iterate through the image files in each folder
    for file_name in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file_name)

        # Skip any non-image files
        if not file_name.lower().endswith(('.jpg', '.jpeg', '.png', '.gif')):
            continue

            
        image = cv2.imread(file_path)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        faces = faceCascade.detectMultiScale(gray,scaleFactor=1.1, minNeighbors=10, minSize=(40, 40))
    
        if len(faces) > 0:
        
          for i, (x,y,w,h) in enumerate(faces):
      
              # To draw a rectangle in a face
             face = image[y:y+h, x:x+w]
             image_file = os.path.join(destination_dir, f"image_{count}.jpg")
             cv2.imwrite(image_file, face)
        count+=1
        break
    if count > 700:
        break
print("Images copied successfully!")

Images copied successfully!


In [11]:
import glob

source_dir = glob.glob("./My/*")

destination_dir = "./Zahra"

In [13]:
count = 0 
os.makedirs(destination_dir, exist_ok=True)
for file_name in source_dir:
    if not file_name.lower().endswith(('.jpg', '.jpeg', '.png', '.gif')):
            continue
    image = cv2.imread(file_name)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray,scaleFactor=1.1, minNeighbors=10, minSize=(40, 40))
    
    if len(faces) > 0:
        
       for i, (x,y,w,h) in enumerate(faces):
      
        # To draw a rectangle in a face
        face = image[y:y+h, x:x+w]
        image_file = os.path.join(destination_dir, f"image_{count}.jpg")
        cv2.imwrite(image_file, face)

        count += 1
print("Face images saved successfully!")         

Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS

Face images saved successfully!


Invalid SOS parameters for sequential JPEG


In [127]:
import glob

my_images = glob.glob("./Zahra/*")
other_images = glob.glob("./Other/*")

In [128]:
target_size = (128,128)

In [129]:
import cv2
import numpy

def preprocess_img(filepath):
    
  try:
    img = cv2.imread(filepath)
    
    img = cv2.resize(img,target_size)

    img_array = np.array(img).flatten()
    #img_array = np.array(img)
    
    #img_array = img_array / 255.0
  
    return img_array

  except Exception as e:
                print(f"Error processing image {filepath}: {e}")


In [130]:
images = []
labels = []

In [131]:
for path in my_images:
    
    img_array = preprocess_img(path)
    label = 1
    
    images.append(img_array)
    labels.append(label)

In [132]:
for path in other_images:
    
    img_array = preprocess_img(path)
    label = 0
    
    images.append(img_array)
    labels.append(label)

In [133]:
images = np.array(images, dtype=np.uint8)
labels = np.array(labels, dtype=np.uint8)

In [134]:
len(images)

1092

## Split the data into training and testing

In [135]:
from sklearn.model_selection import train_test_split
import numpy as np

images = np.array(images)
labels = np.array(labels)
train_images, test_images, train_labels, test_labels = train_test_split(images, labels, train_size=0.8, random_state=42)

## Train model

Random Forest

In [136]:
from sklearn.ensemble import RandomForestClassifier

X_train = train_images
X_test = test_images

X_train_reshape = train_images.reshape(train_images.shape[0], -1)
X_test_reshape = test_images.reshape(test_images.shape[0], -1)


# Create a Random Forest classifier with 100 trees
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train_reshape, train_labels)

RandomForestClassifier()

In [137]:
rf_pred = rf.predict(X_test_reshape)

In [138]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

accuracy = accuracy_score(test_labels, rf_pred)
precision = precision_score(test_labels, rf_pred)
recall = recall_score(test_labels, rf_pred)
f1_score = f1_score(test_labels, rf_pred)
conf_mat = confusion_matrix(test_labels, rf_pred)


# Print the metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 score: {f1_score}")
print(f"confusion_matrix:\n {conf_mat}")

Accuracy: 0.9726027397260274
Precision: 1.0
Recall: 0.9310344827586207
F1 score: 0.9642857142857143
confusion_matrix:
 [[132   0]
 [  6  81]]


SVM

In [139]:
from sklearn.svm import SVC

svm = SVC(C=10, kernel='poly', gamma='auto')

svm.fit(X_train_reshape, train_labels)


svm_pred = svm.predict(X_test_reshape)

In [140]:
accuracy = accuracy_score(test_labels, svm_pred)
conf_mat = confusion_matrix(test_labels, svm_pred)

# Print the metrics
print(f"Accuracy: {accuracy}")
print(f"confusion_matrix:\n {conf_mat}")

Accuracy: 0.9497716894977168
confusion_matrix:
 [[125   7]
 [  4  83]]


LogisticRegression

In [141]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train_reshape, train_labels)
logreg_pred = logreg.predict(X_test_reshape)

/home/asus/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [142]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

accuracy = accuracy_score(test_labels, logreg_pred)
precision = precision_score(test_labels, logreg_pred)
recall = recall_score(test_labels, logreg_pred)
f1_score = f1_score(test_labels, logreg_pred)
conf_mat = confusion_matrix(test_labels, logreg_pred)


# Print the metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 score: {f1_score}")
print(f"confusion_matrix:\n {conf_mat}")

Accuracy: 0.9726027397260274
Precision: 0.9550561797752809
Recall: 0.9770114942528736
F1 score: 0.9659090909090908
confusion_matrix:
 [[128   4]
 [  2  85]]


In [143]:
test_probs = logreg.predict_proba(X_test_reshape)[:, 1]

best_accuracy = 0
best_threshold = 0
for threshold in np.linspace(0, 1, 101):
    predicted_labels = (test_probs >= threshold).astype(int)
    accuracy = accuracy_score(test_labels, predicted_labels)
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_threshold = threshold

predicted_labels = (test_probs >= best_threshold).astype(int)

In [144]:
test_accuracy = accuracy_score(test_labels, predicted_labels)
test_precision = precision_score(test_labels, predicted_labels)
test_recall = recall_score(test_labels, predicted_labels)
test_conf_mat = confusion_matrix(test_labels, predicted_labels)

# Print the metrics
print("Best threshold:", best_threshold)
print(f"Accuracy: {test_accuracy}")
print(f"Precision: {test_precision}")
print(f"Recall: {test_recall}")
print(f"confusion_matrix:\n {test_conf_mat}")

Best threshold: 0.2
Accuracy: 0.9726027397260274
Precision: 0.9550561797752809
Recall: 0.9770114942528736
confusion_matrix:
 [[128   4]
 [  2  85]]


In [145]:
import pickle

with open("model-face.pkl", "wb") as f:
    pickle.dump(rf, f)

In [3]:
import pickle

with open("model-face.pkl", 'rb') as f:
    model = pickle.load(f)

In [ ]:
import cv2
import numpy as np


face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Define the number of forms to start before face recognition is enabled
forms_started = 1
max_forms = 20

frames = []


cap = cv2.VideoCapture(0)
who = None
who_faces = None



try:
    while True:
       ret, frame = cap.read()
       if not ret:
           break

            
       gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
       faces = face_cascade.detectMultiScale(gray,scaleFactor=1.1, minNeighbors=10, minSize=(40, 40))
    
       if len(faces) > 0:
        
         for i, (x,y,w,h) in enumerate(faces):
      
            # To draw a rectangle in a face
            face = frame[y:y+h, x:x+w]
            frames.append(face)
            
       if forms_started >= max_forms:
          who = frame
          who_faces = faces
          break
            
       forms_started+=1
     
except:
    print(f'Video has ended..')  

cap.release()
cv2.destroyAllWindows()


# Define the number of consecutive face recognitions required for entry
required_recognitions = 5
consecutive_recognitions = 0


total = 0
for img in frames:

    img = cv2.resize(img,(128, 128))
    img_array = np.array(img).flatten()


    predict =  model.predict(img_array.reshape(1, -1))
    total+=1
    if predict ==1 :
        consecutive_recognitions +=1
        0
if consecutive_recognitions > required_recognitions : 
    color = (0, 255, 0)  
    prob = (consecutive_recognitions / total)*100
    label = f'Hello Zahra    {prob}%'
else:
    color = (0, 0, 255)  
    prob = (1- (consecutive_recognitions / total))*100
    label = f'can not login       {prob}%'


if len(who_faces) > 0:
   for i, (x,y,w,h) in enumerate(faces):
      
      # To draw a rectangle in a face
      cv2.rectangle(who,(x,y),(x+w,y+h),color,2)
      cv2.putText(who, label, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, color, 2)

   cv2.imshow("image",who)
   cv2.waitKey(0)
   cv2.destroyAllWindows()
